[alias]
"@app" = "./src/app"
"@app/*" = "./src/app/*"
"@features" = "./src/features"
"@features/*" = "./src/features/*"
"@shared" = "./src/shared"
"@shared/*" = "./src/shared/*"
"@lib" = "./src/lib"
"@lib/*" = "./src/lib/*"
"@runtime" = "./src/shared/runtime"
"@runtime/*" = "./src/shared/runtime/*"
"@platform" = "./src/platform"
"@platform/*" = "./src/platform/*"
